config/routes.rb
Rails.application.routes.draw do
  resources :polls do
    resources :questions
  end #/polls/1/questions

   root 'polls#index'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates_presence_of :title
  has_many :questions
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :poll
  has_many :possible_answers
  accepts_nested_attributes_for :possible_answers, reject_if: proc { |attributes| attributes['title'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_poll
  before_action :set_kind_questions
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @poll.questions.build
    5.times { @question.possible_answers.build }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = @poll.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @poll, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :kind, :poll_id, {possible_answers_attributes: [:title, :question_id]})
    end

    def set_kind_questions
      @kind_options = [
        ["Open Answer", "open"],
        ["Multiple Choice", "choice"],
      ]
    end

    def set_poll
      @poll = Poll.find params[:poll_id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Surveys", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          =link_to "Polls", polls_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pollapp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render "nav"
    .container
    = yield

app/views/polls/_form.html.haml
= form_for @poll do |f|
  - if @poll.errors.any?
    #error_explanation
      %h2= "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
      %ul
        - @poll.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

app/views/polls/index.html.haml
%h1 Listing polls

%ul
  - @polls.each do |poll|
    %li
    =link_to poll.title, poll
    |
    = link_to 'Edit', edit_poll_path(poll)
    = link_to 'Destroy', poll, :method => :delete, :data => { :confirm => 'Are you sure?' }
    = link_to 'Add question', new_poll_question_path(poll), class: "btn btn-default"

%p= link_to 'New Poll', new_poll_path, class: "btn btn-primary"

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
%h1=@poll.title

%p.btn-group
  = link_to 'Edit', edit_poll_path(@poll), class: "btn btn-default"
  = link_to 'Back', polls_path, class: "btn btn-default"
  = link_to 'Add question', new_poll_question_path(@poll), class: "btn btn-default"

%h2 Questions

%ul
  -@poll.questions.each do |questions|
    %li
      =questions.title
      %ul
        -question.possible_answers.each do |possible_answer|
          %li=possible_answer.title

app/views/questions/_form.html.haml
= form_for [ @poll, @question ] do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    = f.text_field :title, class: "form-control"

  %p
    = f.label :kind

  .radio
    -@kind_options.each do |option|
      %label
        =f.radio_button :kind, option[1]
        =option[0]


        =f.fields_for :possible_answers do |c|
          %p
            =c.text_field :title, placeholder: "Type your choice", class: "form-control"

  %p
    =f.submit 'Save', class: "btn btn-primary"

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th Title
      %th Kind
      %th Poll
      %th
      %th
      %th

    - @questions.each do |question|
      %tr
        %td= question.title
        %td= question.kind
        %td= question.poll
        %td= link_to 'Show', [ @poll, question ]
        %td= link_to 'Edit', edit_poll_question_path(@poll, question)
        %td= link_to 'Destroy', [ @poll, question ], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', @poll

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @question.title
%p
  %b Kind:
  = @question.kind
%p
  %b Poll:
  = @question.poll

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path